application: profileapps
version: 2
api_version: 1
runtime: python
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets
  
- url: /
  script: home.py

- url: /gangaeyam
  script: others.py
    
- url: /gangaeyam/.*
  script: others.py
      
- url: /.*
  script: userprofile.py
